- name: Copy backend app
  copy:
    src: ../../backend
    dest: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: '0750'
    directory_mode: yes

- name: Install dependencies for npm
  shell:  |
    pm2 stop default
  args:
    chdir: /home/ubuntu/backend

- name: Start app
  shell: pm2 start npm -- run start
  args:
    chdir: /home/ubuntu/backend