- name: install dependencies
  become: true
  package:
    name:
      - nodejs
      - npm
    state: latest
    update_cache: yes
  register: dependency_output

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present 
  register: npm_output

- name: configure ec2 for nmp run and install
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm outdated --parseable --depth=0 | cut -d: -f4 | xargs npm install
    apt install 6.14.4+ds-1ubuntu2
    npm audit fix --force
    rm -rf node_modules package-lock.json && npm install && npm start


- name: install and build package
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build

- name: Start pm2
  shell: |
    cd /home/ubuntu/backend 
    pm2 stop default
    pm2 start npm --name backend -- start


