- name: Copy backend app
  become: true
  copy:
    src: ../../backend
    dest: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: '0755'
    directory_mode: yes
  no_output_timeout: 30m

#- name: Change folder permissions
#  become: true
#  shell: |
#    chown -R ubuntu:ubuntu /home/ubuntu/backend

#- name: to update the apt packages
#  become: true
#  apt:
#    update_cache: yes

#- name: upgrade packages
#  become: true
#  apt:
#    upgrade: yes

- name: install dependencies
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: start app
  shell: |
    cd /home/ubuntu/backend/dist
    pm2 stop default
    pm2 start npm --name 'udapeople' -- start
    pm2 ls