- name: create application user
  become: True
  user:
    name: "{{ app_user }}"

- name: install dependencies
  become: True
  package:
    name:
      - nodejs
      - npm
    state: latest
    update_cache: yes

- name: install pm2
  become: True
  npm:
    name: pm2
    global: yes
    production: "{{ environment == 'prod' | bool }}"

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: start app
  shell: |
    cd /home/ubuntu/backend/dist
    pm2 stop default
    pm2 start npm --name 'udapeople' -- start
    pm2 ls
    
- name: create install dir
  become: True
  file:
    state: directory
    path: "{{ installation_directory }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'

- name: copy archive
  become: True
  unarchive:
    src: ../../artifact.tar.gz
    dest: "{{ installation_directory }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'

- name: install npm {{ npm_version }}
  become: True
  shell: npm install -g n && n {{ npm_version }}
  args:
    chdir: "{{ installation_directory }}"

- name: start pm2
  become: True
  shell: pm2 start npm --name backend -- run start
  args:
    chdir: "{{ installation_directory }}"

    # apt list --upgradable