- name: install dependencies
  become: true
  package:
    name:
      - nodejs
      - npm
    state: latest
    update_cache: yes
  register: dependency_output

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present 
  register: npm_output

- name: chane backend folder permissions
  become: true
  shell: |
  chown -R ubuntu:ubuntu /home/ubuntu/backend




