- name: Copy zipped artifact to EC2 instance and Unzip
  ansible.builtin.copy:
    src: ../../artifact.tar.gz
    dest: "{{ application_directory }}"
  tags:
    - prereqs

- name: Install npm modules
  community.general.npm:
    path: "{{ application_directory }}"
  tags:
    - npm
    - setup

- name: Stop default app
  command: pm2 stop default
  args:
    chdir: "{{ application_directory }}"
  tags:
    - npm
    - stop_default

- name: Start our app
  command: pm2 start npm -- start
  args:
    chdir: "{{ application_directory }}"
  tags:
    - npm
    - start_app