---
- name: "deploy backend"
  become_user: true
  unarchive:
    src: ../../artifact-backend.tar.gz
    dest: ~/

- name: "run backend"
  become_user: true
  shell: |
    ls -la
    cd ~/backend/
    ls -la
    npm i
    pm2 stop default
    pm2 start npm -- start