- name: install dependencies
  become: true
  package:
    name:
      - nodejs
      - npm
    state: latest
    update_cache: yes
  register: dependency_output

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present 
  register: npm_output

- name: install npm & chnage to 13.8.0 version
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install -g n
    n 13.8.0
    chown -R ubuntu:ubuntu /home/ubuntu/backend




