# ---
# - name: "deploy backend"
#   become_user: true
#   unarchive:
#     src: ../../artifact-backend.tar.gz
#     dest: ~/

# - name: "run backend"
#   become_user: true
#   shell: |
#     ls -la
#     cd ~/backend/
#     ls -la
#     npm i
#     pm2 stop default
#     pm2 start npm -- start

- name: create backend directory
  become: yes
  file:
    # path: ~/backend
    path: /home/ubuntu/backend/
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

# - name: copy backend files
#   become_user: true
#   unarchive:
#     src: ../../artifact-backend.tar.gz
#     dest: ~/backend/artifact-backend.tar.gz

- name: copy backend files
  become: yes
  copy:
    # src: ~/project/artifact-backend.tar.gz
    # dest: ~/backend/artifact-backend.tar.gz
    src: /root/project/artifact-backend.tar.gz
    dest: /home/ubuntu/backend/
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: unpack backend files
  become: yes
      # cd ~/backend
  shell: |
    cd /home/ubuntu/backend/
    tar -xvf artifact-backend.tar.gz
    rm -f artifact-backend.tar.gz

- name: place .env file
  become: yes
  vars:
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT')}}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
  template:
    src: env
    dest: ~/backend/.env
    mode: '0700'


# - name: start the app 
#   become: yes
#   shell: |
#     cd ~/backend
#     npm install
#     pm2 stop default
#     pm2 start npm  -- start
#     cd dist
#     pm2 start main.js --update-env

- name: "Install nodejs and npm."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2."
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

    
- name: "Start server"
  become: true
  shell: |
    pwd
    ls
    cd dist
    pm2 start npm --name 'udapeople' -- start
  args:
    chdir: /home/ubuntu/backend/